# Generated by Django 5.0.6 on 2024-05-31 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_image"),
    ]

    operations = [
        migrations.RenameField(model_name="post", old_name="image", new_name="img",),
    ]
